server:
  port: 8090
spring:
  application:
    name: MyAPIGateway
routes:
  - id: PaymentService-01
    uri: http://localhost:8080/
    predicates:
      - Path=/payment/**
  - id: MyApplicationService-02
    uri: http://localhost:8081/
    predicates:
      - Path=/service2/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/