
spring:
  datasource:
    url: jdbc:postgresql://gblinuxlab:5432/mypostgresdb
    username: myuser
    password: springdbPassw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update