server:
  port: 8080
spring:
  application:
    name: MyAPIGateway
routes:
  - id: Tasks
    uri: http://localhost:8090/
    predicates:
      - Path=/tasks/**
  - id: Users
    uri: http://localhost:8091/
    predicates:
      - Path=/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/